#ifndef HardwareComponent_h
#define HardwareComponent_h

#include <systemc.h>

#include <map>
#include <set>

SC_MODULE(HardwareComponent) {
	typedef enum DataType_t{
		DataType_vector,
		DataType_bit,
		DataType_integer
	}DataType;

	typedef struct PortInfo_t{
		std::string name;
		DataType type;
		int size;
	}PortInfo;

/*this information table should be generated by the ComponentDatabase or ComponentLocator*/
	typedef struct HardwareComponentInfo_t{
	/*maybe put here the files and dependencies*/
    std::string name;
    std::vector< PortInfo > inputs;
    std::vector< PortInfo > outputs;

		/*generic is still not clear*/
    std::map<std::string, std::pair<std::string, std::string> > genericTable;
		std::set<std::string> dependencyFiles;

	}HardwareComponentInfo;


	private:

	public:
		std::map<std::string, sc_port_base*> ports;
		bool isDynamic;
		HardwareComponentInfo *componentInfo;
		//table containing information about the component
	
	public:
		SC_HAS_PROCESS(HardwareComponent);
		HardwareComponent(sc_module_name name, HardwareComponentInfo *infoTable);

		/*functions used in dynamic creation*/
		void addInput(std::string name, DataType type, int size = 1);
		void addOutput(std::string name, DataType type, int size = 1);
		void addInout(std::string name, DataType type, int size = 1);
		sc_port_base* getPort(std::string name);
		void portMap(std::string selfPortName, sc_port_base* port);
		void portMap(std::string selfPortName, sc_signal_resolved* signal);
		void addChildComponent(sc_module *child);

	private:
		void addPortAttributes(std::string name, DataType type, int size);

};

#endif
