#include "XilinxProjectHandler.h"

#include <fstream>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

using namespace std;

XilinxProjectHandler::XilinxProjectHandler(std::string projectName, std::string projectPath, std::string reconfRegionName){
	this->projectName = projectName;
	this->projectPath = projectPath;
	this->reconfRegionName = reconfRegionName;
	buildProjectFile(projectPath);
}

void XilinxProjectHandler::buildProjectFile(std::string projectFilePath){

}

void XilinxProjectHandler::addFile(std::string file, bool generatedFile){
	this->usedFiles.push_back(file);
	if(!generatedFile)
		copyFile(file, projectPath);
	else
		filesInProject.push_back(file);
}

void XilinxProjectHandler::copyFile(std::string file, std::string destPath){
	ifstream ifs(file.c_str(), std::ios::binary);
	string fileName = file.substr(file.find_last_of("/")+1,file.size());
	cout<<"copying file name "<<file << " to "<<endl<<destPath + "/" + fileName<<endl;
	ofstream ofs((destPath+"/"+fileName).c_str(), std::ios::binary);
	ofs << ifs.rdbuf();
	ofs.close();
	ifs.close();
	filesInProject.push_back(destPath+"/"+fileName);
}

void XilinxProjectHandler::removeFile(std::string file){

	for(vector<string>::iterator it = usedFiles.begin(); it!= usedFiles.end(); it++){
		if (*it == file){
			usedFiles.erase(it);
			break;
		}
	}
}

void XilinxProjectHandler::generateConfigFiles(){
	string projectFile = projectPath + "/" + projectName + ".prj";
	ofstream prjFile;
	prjFile.open(projectFile.c_str());
	prjFile<<"#This project file was generated by the HardwareReconfiguration API"<<endl;


	for(vector<string>::iterator fileIt = filesInProject.begin(); fileIt!= filesInProject.end(); fileIt++){
		if(fileIt->rfind(".vhd") == fileIt->size() - 4 ||
			 fileIt->rfind(".vhdl") == fileIt->size() - 5)
			prjFile<<"vhdl work "<<*fileIt<<endl;
		else if(fileIt->rfind(".v") == fileIt->size() - 2)
			prjFile<<"verilog work "<<*fileIt<<endl;
//		else
//			prjFile<<*fileIt<<endl;
	}
		

	prjFile.close();

	string optionsFile = projectPath + "/" + projectName + ".opt";
	ofstream optFile;
	optFile.open(optionsFile.c_str());

	optFile<<"#This options file was generated by the HardwareReconfiguration API"<<endl;

	/*copyied from xst_mixed.opt*/
	optFile<< "Program xst"<<endl;
	optFile<<"\t"<< "-ifn <design>_xst.scr;"<<endl;
	optFile<<"\t"<< "-ofn <design>_xst.log;"<<endl;
	optFile<<"\t"<< "-intstyle xflow;"<<endl;
	optFile<<"\t"<< "ParamFile: <design>_xst.scr"<<endl;

	optFile<<"\t"<<"\t"<< "\"run\";" << endl;
	optFile<<"\t"<<"\t"<< "\"-ifn <synthdesign>\";" << endl;
	optFile<<"\t"<<"\t"<< "\"-ifmt mixed\";" << endl;
	optFile<<"\t"<<"\t"<< "\"-ofn <design>\";" << endl;
	optFile<<"\t"<<"\t"<< "\"-ofmt ngc\";" << endl;
	optFile<<"\t"<<"\t"<< "\"-top <design>\";" << endl;
	optFile<<"\t"<<"\t"<< "\"-p <partname>\";" << endl;
	optFile<<"\t"<<"\t"<< "\"-verilog2001 YES\";" << endl;
	optFile<<"\t"<<"\t"<< "\"-iobuf NO\";" << endl; //disable IOBUF due PR restrictions
	optFile<<"\t"<<"\t"<< "\"-bufg 0\";" << endl; //disable clock buffering due to PR restrictions

	optFile<<"\t"<< "End ParamFile"<<endl;
	optFile<<"End Program xst"<<endl;

	optFile.close();


	this->prjFileName = projectFile;
	this->optFileName = optionsFile;

}

//TODO error handling

void XilinxProjectHandler::compileProject(std::string hardwareProjectName, std::string hardwareProjectPath){
	
	generateConfigFiles();

	char * workingDir = getcwd(0, NULL);
		
	char * xflowPath = getenv("XILINX_XFLOW_PATH");
	string xflowCommand(xflowPath);

	chdir(projectPath.c_str());
	xflowCommand += string("/xflow.exe") + string(" -p ") + string(" xc5vlx110tff1136-1 ") + string(" -synth ") + string(projectName + ".opt ") + "./" + projectName + ".prj";

	system(xflowCommand.c_str());



	string planAheadScriptcommand(workingDir);
	string bitGenScriptcommand(workingDir);

	string pathForNgcFile = projectPath + "/" + projectName + ".ngc";

	chdir((planAheadScriptcommand + "/xilinxScripts").c_str());
	planAheadScriptcommand += string("/xilinxScripts/planAheadCompileRM.sh ") + hardwareProjectName + " " + hardwareProjectPath + " " + reconfRegionName + " rm1 " + pathForNgcFile;
	
	cout << "COMPILING DESIGNS" << endl;
	system(planAheadScriptcommand.c_str());
	
	cout << "GENERATING BITSTREAMS" << endl;
	bitGenScriptcommand += string("/xilinxScripts/planAheadGenerateRMBitStream.sh ") + hardwareProjectName + " " + hardwareProjectPath + " " + reconfRegionName + " rm1 " + pathForNgcFile;

	system(bitGenScriptcommand.c_str());

//	cout << "compilation string: "<<endl<< planAheadScriptcommand <<endl;	

}

