
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.4 EDK_P.49d
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xiic.h"

/*
* The configuration table for devices
*/

XIic_Config XIic_ConfigTable[] =
{
	{
		XPAR_IIC_EEPROM_DEVICE_ID,
		XPAR_IIC_EEPROM_BASEADDR,
		XPAR_IIC_EEPROM_TEN_BIT_ADR,
		XPAR_IIC_EEPROM_GPO_WIDTH
	},
	{
		XPAR_XPS_IIC_1_DEVICE_ID,
		XPAR_XPS_IIC_1_BASEADDR,
		XPAR_XPS_IIC_1_TEN_BIT_ADR,
		XPAR_XPS_IIC_1_GPO_WIDTH
	},
	{
		XPAR_XPS_IIC_2_DEVICE_ID,
		XPAR_XPS_IIC_2_BASEADDR,
		XPAR_XPS_IIC_2_TEN_BIT_ADR,
		XPAR_XPS_IIC_2_GPO_WIDTH
	}
};


