include ../environment.mk
#includes required 

LDFLAGS+= -L../lib -lhardwarereconfigurationapi

SRC_FOLDERS = $(CURDIR) \
						  $(CURDIR)/ArdupilotCommLink

EXECUTABLE = HardwareReconfTests

clean:: clean_executable


