-- This file was auto generated by the HardwareProjectXmlParser

library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_unsigned.all;

entity WP_L1_NavigationController is
port (
ABVectorX: in std_logic_vector(31 downto 0);
ABVectorY: in std_logic_vector(31 downto 0);
K_L1: in std_logic_vector(31 downto 0);
L1_dist: in std_logic_vector(31 downto 0);
L1_dist_min: in std_logic_vector(31 downto 0);
airUnitVectorX: in std_logic_vector(31 downto 0);
airUnitVectorY: in std_logic_vector(31 downto 0);
bearing_error: out std_logic_vector(31 downto 0);
clk: in std_logic;
groundspeed: in std_logic_vector(31 downto 0);
gsVectorX: in std_logic_vector(31 downto 0);
gsVectorY: in std_logic_vector(31 downto 0);
last_nu: out std_logic_vector(31 downto 0);
lateral_acceleration_dem: out std_logic_vector(31 downto 0);
max_nu: in std_logic_vector(31 downto 0);
min_nu: in std_logic_vector(31 downto 0);
nav_bearing: out std_logic_vector(31 downto 0);
nav_bearing_cd_condition: in std_logic;
nu: out std_logic_vector(31 downto 0);
nu_limit: in std_logic_vector(31 downto 0);
sin_nu1_max: in std_logic_vector(31 downto 0);
sin_nu1_min: in std_logic_vector(31 downto 0);
wpa_reference: in std_logic
);
end WP_L1_NavigationController;

architecture arch of WP_L1_NavigationController is
-- Component Declaration

component AP_Navigation_controll
port (
	ABVectorX: in std_logic_vector(31 downto 0);
	ABVectorY: in std_logic_vector(31 downto 0);
	K_L1: in std_logic_vector(31 downto 0);
	L1_dist: in std_logic_vector(31 downto 0);
	L1_dist_min: in std_logic_vector(31 downto 0);
	airUnitVectorX: in std_logic_vector(31 downto 0);
	airUnitVectorY: in std_logic_vector(31 downto 0);
	clk: in std_logic;
	groundspeed: in std_logic_vector(31 downto 0);
	gsVectorX: in std_logic_vector(31 downto 0);
	gsVectorY: in std_logic_vector(31 downto 0);
	max_nu: in std_logic_vector(31 downto 0);
	min_nu: in std_logic_vector(31 downto 0);
	nav_bearing_cd_condition: in std_logic;
	nu_limit: in std_logic_vector(31 downto 0);
	sin_nu1_max: in std_logic_vector(31 downto 0);
	sin_nu1_min: in std_logic_vector(31 downto 0);
	wpa_reference: in std_logic;
	bearing_error: out std_logic_vector(31 downto 0);
	last_nu: out std_logic_vector(31 downto 0);
	lateral_acceleration_dem: out std_logic_vector(31 downto 0);
	nav_bearing: out std_logic_vector(31 downto 0);
	nu: out std_logic_vector(31 downto 0)
);
end component AP_Navigation_controll;


-- Signal Declaration

begin


-- Architectural Declaration --



-- component's port maps 

AP_Navigation_controll_inst:AP_Navigation_controll port map (
ABVectorX=>ABVectorX,
ABVectorY=>ABVectorY,
K_L1=>K_L1,
L1_dist=>L1_dist,
L1_dist_min=>L1_dist_min,
airUnitVectorX=>airUnitVectorX,
airUnitVectorY=>airUnitVectorY,
clk=>clk,
groundspeed=>groundspeed,
gsVectorX=>gsVectorX,
gsVectorY=>gsVectorY,
max_nu=>max_nu,
min_nu=>min_nu,
nav_bearing_cd_condition=>nav_bearing_cd_condition,
nu_limit=>nu_limit,
sin_nu1_max=>sin_nu1_max,
sin_nu1_min=>sin_nu1_min,
wpa_reference=>wpa_reference,
bearing_error=>bearing_error,
last_nu=>last_nu,
lateral_acceleration_dem=>lateral_acceleration_dem,
nav_bearing=>nav_bearing,
nu=>nu
); --AP_Navigation_controll_inst


-- signal maps --


end arch;
