-- This file was auto generated by the CommunicationHardwareGenerator

-- Component Declaration

component APNavigationControl_communicationHardware is
generic (
	commHardware_addressWidth : integer := 32;
	commHardware_dataWidth : integer := 32
);
port (
	commHardware_address: in std_logic_vector(commHardware_addressWidth - 1 downto 0);
	commHardware_clk: in std_logic;
	commHardware_dataIn: in std_logic_vector(commHardware_dataWidth - 1 downto 0);
	commHardware_dataOut: out std_logic_vector(commHardware_dataWidth - 1 downto 0);
	commHardware_mode: in std_logic
);
end componentAPNavigationControl_communicationHardware;

-- Component Declaration end

